language: c

script: tools/ci.sh

compiler:
  - clang
  - gcc
  - scan-build

# travis doesn't currently have scan-build and valgrind by default
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install clang valgrind
